version: 1.0.{build}
configuration: Release
before_build:
- cmd: nuget restore -verbosity detailed
build:
  verbosity: minimal
artifacts:
- path: '\src\nancy-api\bin\$(configuration)\'
  name: nancy-api